// Generated by CoffeeScript 1.12.2
var app, express, express_nunjucks, njk, nunjucks, server;

nunjucks = require("nunjucks");

express_nunjucks = require("express-nunjucks");

express = require("express");

app = express();

app.set("views", __dirname + "/templates");

njk = express_nunjucks(app, {
  watch: true,
  noCache: true
});

app.get("/", function(req, res) {
  return res.render("index.html");
});

server = app.listen(3000, function() {
  var host, port;
  host = server.address().address;
  port = server.address().port;
  return console.log("Bill Manager listening at http://" + host + ":" + port);
});
